CONNECTION_STRING: ${env:CONNECTION_STRING}

CAPTCHA_SECRET_KEY: ${env:CAPTCHA_SECRET_KEY}
MAPBOX_API_TOKEN: ${env:MAPBOX_API_TOKEN}

AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
AUTH0_MGMT_CLIENT_ID: ${env:AUTH0_MGMT_CLIENT_ID}
AUTH0_MGMT_CLIENT_SECRET: ${env:AUTH0_MGMT_CLIENT_ID}
AUTH0_PUBLIC_CLIENT_ID: ${env:AUTH0_PUBLIC_CLIENT_ID}
AUTH0_PUBLIC_CLIENT_SECRET: ${env:AUTH0_PUBLIC_CLIENT_ID}
