CONNECTION_STRING: ${env:CONNECTION_STRING}

CAPTCHA_SECRET_KEY: ${env:CAPTCHA_SECRET_KEY}
MAPBOX_API_TOKEN: ${env:MAPBOX_API_TOKEN}
FCM_SERVER_KEY: ${env:FCM_SERVER_KEY}

APPROVAL_KEY: ${env:APPROVAL_KEY}
STORE_REVIEW_PASSWORD: ${env:STORE_REVIEW_PASSWORD}
STORE_REVIEW_OTP: ${env:STORE_REVIEW_OTP}

AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
AUTH0_MGMT_CLIENT_ID: ${env:AUTH0_MGMT_CLIENT_ID}
AUTH0_MGMT_CLIENT_SECRET: ${env:AUTH0_MGMT_CLIENT_SECRET}
AUTH0_PUBLIC_CLIENT_ID: ${env:AUTH0_PUBLIC_CLIENT_ID}
AUTH0_PUBLIC_CLIENT_SECRET: ${env:AUTH0_PUBLIC_CLIENT_SECRET}
