service:
  name: samaritan-app-api

plugins:
  - serverless-webpack

package:
  include:
    - .webpack/*.js
    - .webpack/*.map

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  environment: ${file(./serverless/environment.yml)}
  httpApi:
    payload: '2.0'
    authorizers:
      auth0Authorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://samaritan-app.eu.auth0.com/
        audience:
          - https://api.samaritan-app.eu

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: yarn
    concurrency: 5
    individually: true
  prune:
    automatic: true
    number: 3

functions:
  ${file(./serverless/functions.yml)}

