service:
  name: samaritan-app-api

plugins:
  - serverless-webpack
  - '@haftahave/serverless-ses-template'

package:
  include:
    - .webpack/*.js
    - .webpack/*.map

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  environment: ${file(./serverless/environment.yml)}
  iam:
    role:
      statements:
        - Effect: Allow
          Resource:
            - arn:aws:ses:eu-central-1:070386867730:identity/samaritan-app.eu
          Action:
            - ses:SendTemplatedEmail
          Condition:
            StringEquals:
              'ses:FromAddress': 'crew@samaritan-app.eu'
  httpApi:
    payload: '2.0'
    authorizers:
      auth0Authorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://samaritan-app.eu.auth0.com/
        audience:
          - https://api.samaritan-app.eu

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: yarn
    concurrency: 5
    individually: true
  prune:
    automatic: true
    number: 3
  sesTemplatesAddStageAlias: false
  sesTemplatesConfigFile: '../../scripts/template.config.js'

functions:
  ${file(./serverless/functions.yml)}

